/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

/**
 *
 * @author Carlos
 */
public class Calculadora extends javax.swing.JFrame {
private boolean punto=true;
    String v1,v2,sig,cont;
Double res;
    /**
     * Creates new form calculador
     */
    public Calculadora() {
        initComponents();
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        btraiz = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        btx2 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt1x = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        btdiv = new javax.swing.JButton();
        btborrar = new javax.swing.JButton();
        btmul = new javax.swing.JButton();
        btex = new javax.swing.JButton();
        btres = new javax.swing.JButton();
        btxy = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btp = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btmm = new javax.swing.JButton();
        btsuma = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btigual = new javax.swing.JButton();
        btc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 90));

        bt4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel1.add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 90));

        bt7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel1.add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 90));

        btraiz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btraiz.setText("RAIZ");
        btraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btraizActionPerformed(evt);
            }
        });
        jPanel1.add(btraiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 90));

        txt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 90));

        btx2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btx2.setText("X^2");
        btx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btx2ActionPerformed(evt);
            }
        });
        jPanel1.add(btx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 120, 90));

        bt2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 120, 90));

        bt5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel1.add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 120, 90));

        bt1x.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt1x.setText("1/X");
        bt1x.setToolTipText("");
        bt1x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1xActionPerformed(evt);
            }
        });
        jPanel1.add(bt1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, 90));

        bt8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, 90));

        btdiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btdiv.setText("/");
        btdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdivActionPerformed(evt);
            }
        });
        jPanel1.add(btdiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 120, 90));

        btborrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btborrar.setText("<--");
        btborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btborrarActionPerformed(evt);
            }
        });
        jPanel1.add(btborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 120, 90));

        btmul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btmul.setText("X");
        btmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmulActionPerformed(evt);
            }
        });
        jPanel1.add(btmul, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 120, 90));

        btex.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btex.setText("E^X");
        btex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexActionPerformed(evt);
            }
        });
        jPanel1.add(btex, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 120, 90));

        btres.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btres.setText("-");
        btres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresActionPerformed(evt);
            }
        });
        jPanel1.add(btres, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 120, 90));

        btxy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btxy.setText("X^Y");
        btxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxyActionPerformed(evt);
            }
        });
        jPanel1.add(btxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 120, 90));

        bt3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 120, 90));

        bt6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 120, 90));

        bt9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel1.add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 120, 90));

        btp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btp.setText(".");
        btp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpActionPerformed(evt);
            }
        });
        jPanel1.add(btp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 120, 90));

        bt0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        jPanel1.add(bt0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 120, 90));

        btmm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btmm.setText("+-");
        btmm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmmActionPerformed(evt);
            }
        });
        jPanel1.add(btmm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 120, 90));

        btsuma.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btsuma.setText("+");
        btsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsumaActionPerformed(evt);
            }
        });
        jPanel1.add(btsuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 120, 90));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("%");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 120, 90));

        btigual.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btigual.setText("=");
        btigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btigualActionPerformed(evt);
            }
        });
        jPanel1.add(btigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 120, 90));

        btc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btc.setText("C");
        btc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcActionPerformed(evt);
            }
        });
        jPanel1.add(btc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 120, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 630, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"5");
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"2");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"6");
    }//GEN-LAST:event_bt6ActionPerformed

    private void btcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcActionPerformed
        // TODO add your handling code here:
        txt.setText("");
    }//GEN-LAST:event_btcActionPerformed

    private void btmmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmmActionPerformed
        // TODO add your handling code here:
        cont=txt.getText();
        if(cont.length()>0){
            res=(-1)*Double.parseDouble(cont);
            txt.setText(res.toString());
        }
    }//GEN-LAST:event_btmmActionPerformed

   
    
    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"0");
    }//GEN-LAST:event_bt0ActionPerformed

    private void btpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpActionPerformed
        // TODO add your handling code here:
        cont =txt.getText();
        if(cont.length()<=0){
            txt.setText("0.");
        }else
            if(txt.getText().contains(".")){
                
            }else{
                txt.setText(txt.getText()+".");
            punto=false; 
        }
    }//GEN-LAST:event_btpActionPerformed

     public static String operacion(String v1,String v2,String sig){
    Double rescal=0.0;
    String resp;
    if(sig.equals("+")){
        rescal=Double.parseDouble(v1)+Double.parseDouble(v2);
        }else  if(sig.equals("-")){
        rescal=Double.parseDouble(v1)-Double.parseDouble(v2);
        }else  if(sig.equals("*")){
        rescal=Double.parseDouble(v1)*Double.parseDouble(v2);
        }else  if(sig.equals("/")){
        rescal=Double.parseDouble(v1)/Double.parseDouble(v2);
        } else  if(sig.equals("%")){
        rescal=(Double.parseDouble(v1)/100)*Double.parseDouble(v2);
        } 
        else  if(sig.equals("x^y"))
        {
        rescal=Math.pow(Double.parseDouble(v1),Double.parseDouble(v2));
        
        }
    resp=rescal.toString();
    return resp;
        
}
    private void btigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btigualActionPerformed
        // TODO add your handling code here:
        String restotal;
        v2=txt.getText();
        if(!v2.equals("")){
            restotal=operacion(v1,v2,sig);
            txt.setText(restotal);
        }
    }//GEN-LAST:event_btigualActionPerformed

    private void btdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdivActionPerformed
        // TODO add your handling code here:
        if(!txt.getText().equals("")){
            v1=txt.getText();
            sig="/";
            txt.setText("");
        }
    }//GEN-LAST:event_btdivActionPerformed

    private void btresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresActionPerformed
        // TODO add your handling code here:
        if(!txt.getText().equals("")){
            v1=txt.getText();
            sig="-";
            txt.setText("");
        }
    }//GEN-LAST:event_btresActionPerformed

    private void btmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmulActionPerformed
        // TODO add your handling code here:
        if(!txt.getText().equals("")){
            v1=txt.getText();
            sig="*";
            txt.setText("");
        }
    }//GEN-LAST:event_btmulActionPerformed

    private void btborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btborrarActionPerformed
        // TODO add your handling code here:
        cont=txt.getText();
        if(cont.length()>0){
            cont=cont.substring(0,cont.length()-1);;
            txt.setText(cont);
        }
    }//GEN-LAST:event_btborrarActionPerformed

    private void btraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btraizActionPerformed
        // TODO add your handling code here:
        cont=txt.getText();
        if(cont.length()>0){
            res=Math.sqrt(Double.parseDouble(cont));
            txt.setText(res.toString());
        }
    }//GEN-LAST:event_btraizActionPerformed

    private void bt1xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1xActionPerformed
        // TODO add your handling code here:
               cont=txt.getText();
        if(cont.length()>0){
            res=1/(Double.parseDouble(cont));
            txt.setText(res.toString());
        }
    }//GEN-LAST:event_bt1xActionPerformed

    private void btx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btx2ActionPerformed
        // TODO add your handling code here:
       cont=txt.getText();
        if(cont.length()>0){
            res=Math.pow(Double.parseDouble(cont), 2);
            txt.setText(res.toString());
        }
    }//GEN-LAST:event_btx2ActionPerformed

    private void btxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxyActionPerformed
        // TODO add your handling code here:
        if(!txt.getText().equals("")){
            v1=txt.getText();
            sig="x^y";
            txt.setText("");
        }
    }//GEN-LAST:event_btxyActionPerformed

    private void btexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexActionPerformed
        // TODO add your handling code here:
         cont=txt.getText();
        if(cont.length()>0){
            res=Math.exp(Double.parseDouble(cont));
            txt.setText(res.toString());
        }
    }//GEN-LAST:event_btexActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"3");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"7");
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"8");
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"9");
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"1");
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        txt.setText(txt.getText()+"4");
    }//GEN-LAST:event_bt4ActionPerformed

    private void btsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsumaActionPerformed
        // TODO add your handling code here:
        if(!txt.getText().equals("")){
            v1=txt.getText();
            sig="+";
            txt.setText("");
        }
    }//GEN-LAST:event_btsumaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!txt.getText().equals("")){
            v1=txt.getText();
            sig="%";
            txt.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt1x;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btborrar;
    private javax.swing.JButton btc;
    private javax.swing.JButton btdiv;
    private javax.swing.JButton btex;
    private javax.swing.JButton btigual;
    private javax.swing.JButton btmm;
    private javax.swing.JButton btmul;
    private javax.swing.JButton btp;
    private javax.swing.JButton btraiz;
    private javax.swing.JButton btres;
    private javax.swing.JButton btsuma;
    private javax.swing.JButton btx2;
    private javax.swing.JButton btxy;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
